spring:
  datasource:
    url: jdbc:h2:mem:public
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  flyway:
    enabled: false
  sql:
    init:
      mode: always